language: php

php:
  - 7.0

install:
  - composer install

env:
    - APP_KEY=base64:YuUZ7uNEJ2dmoX9531HAsWOH9yZ99sBHUVw1ejRsEk0=

notifications:
  email:
    recipients:
      - jingfu99@gmail.com
    on_success: always
    on_failure: always

script: phpunit -c phpunit.xml --coverage-text
