language: php

php:
  - 7.0

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - jingfu99@gmail.com
    on_success: always
    on_failure: always

script: phpunit -c phpunit.xml --coverage-text
